# Data loading

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/home/jawad/my_jupyter_env/Data_Science_Projects/Urban-Road-Safety-Near-Miss-Analysis/urban_near_miss_dataset_12000.csv")

,Record_ID,City,Day_of_Week,Hour,Weather,Traffic_Level,Vehicle_Type,Road_Type,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
0,1,Peshawar,Thursday,6,Cloudy,Medium,Motorcycle,Main Road,60,51.7,11,82.3,40.2,0
1,2,Karachi,Friday,19,Clear,Medium,Bus,Residential,50,51.8,10,91.1,31.6,0
2,3,Rawalpindi,Friday,14,Clear,Medium,Rickshaw,Residential,50,74.7,11,82.2,44.8,0
3,4,Peshawar,Sunday,10,Rain,High,Car,Main Road,60,39.4,7,74.0,35.6,0
4,5,Rawalpindi,Saturday,7,Rain,Severe,Rickshaw,Highway,100,62.5,8,97.3,57.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11996,Quetta,Tuesday,19,Cloudy,Medium,Motorcycle,Market,50,37.3,31,74.5,37.9,0
11996,11997,Peshawar,Thursday,18,Rain,Severe,Rickshaw,Residential,50,22.7,10,84.4,76.3,1
11997,11998,Lahore,Sunday,13,Clear,Low,Van,Residential,50,41.7,8,98.3,20.8,0
11998,11999,Rawalpindi,Monday,1,Clear,Medium,Bus,Market,50,41.8,25,87.0,25.9,0
11999,12000,Karachi,Friday,4,Clear,Medium,Van,Residential,50,27.9,3,92.5,41.5,0

# ist five rows of the  data sets

In [4]:
df.head()

,Record_ID,City,Day_of_Week,Hour,Weather,Traffic_Level,Vehicle_Type,Road_Type,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
0,1,Peshawar,Thursday,6,Cloudy,Medium,Motorcycle,Main Road,60,51.7,11,82.3,40.2,0
1,2,Karachi,Friday,19,Clear,Medium,Bus,Residential,50,51.8,10,91.1,31.6,0
2,3,Rawalpindi,Friday,14,Clear,Medium,Rickshaw,Residential,50,74.7,11,82.2,44.8,0
3,4,Peshawar,Sunday,10,Rain,High,Car,Main Road,60,39.4,7,74.0,35.6,0
4,5,Rawalpindi,Saturday,7,Rain,Severe,Rickshaw,Highway,100,62.5,8,97.3,57.1,1

# shape of the data sets

In [6]:
df.shape

(12000, 14)

# columns in the data set

In [7]:
df.columns

Index(['Record_ID', 'City', 'Day_of_Week', 'Hour', 'Weather', 'Traffic_Level',
       'Vehicle_Type', 'Road_Type', 'Speed_Limit_kmh', 'Average_Speed_kmh',
       'Pedestrian_Count', 'Visibility_Percent', 'Near_Miss_Score',
       'Incident'],
      dtype='str')